# Bun configuration for spec-kit scripts library

[install]
# Prefer exact versions for reproducibility
exact = true

[install.cache]
# Cache directory for faster installs
dir = "~/.bun/cache"

[install.lockfile]
# Save exact versions in lockfile
save = true

[test]
# Test configuration
root = "./tests"
coverage = true
coverageThreshold = 0
coverageSkipTestFiles = true
coverageReporter = [
  "text",
  "lcov"
]

[run]
# Silent mode for cleaner output in scripts
silent = false
# Automatically install missing packages
autoInstall = true
