version: "1.0"

plugins:
  sync:
    platform: github
    autoSync: true
    conflictStrategy: manual
    github:
      owner: amondnet
      repo: spec-kit-sdk-example
      auth: cli
      # token: ${GITHUB_TOKEN}  # Optional: for token-based auth
